### ISSUE TITLE
no such element: Unable to locate element: {"method":"css selector","selector":"[name="q"]"}

### ISSUE THREAD

**Issue by rgaufman** [lyyka/google-maps-businesses-scraper#3]
When I launch the map, it opens a browser window and I see this:

```python
$ python3 script.py --query="Hairdressers" --places="WC2N"
Moving on to WC2N
Traceback (most recent call last):
  File "/Users/hackeron/google-maps-businesses-scraper/script.py", line 6, in <module>
    scrape(args)
  File "/Users/hackeron/google-maps-businesses-scraper/modules/scraper.py", line 67, in scrape
    q_input = driver.find_element_by_name("q")
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="q"]"}
  (Session info: chrome=89.0.4389.128)
```

![Screenshot 2021-04-18 at 17 27 47](https://user-images.githubusercontent.com/33842342/115152962-67e5f280-a06b-11eb-9566-da9cbc1e2d34.png)

Any ideas?

**Comment by nyolcaserno** [comment]
Did you find the solution? I have the same problem. Thanks! :)

**Comment by nyolcaserno** [comment]
Looking for these lines in screper.py file:

for place in SETTINGS["PLACES"]:
        # Go to the index page
        driver.get(SETTINGS["MAPS_INDEX"])

**Add to this:**
        time.sleep (4)
        elem = driver.find_element_by_css_selector("#yDmH0d > c-wiz > div > div > div > div.NIoIEf > div.G4njw > div.AIC7ge > form > div.lssxud > div > button")
        elem.click()     
        time.sleep (5)

**Comment by Jackahack** [comment]
when i try that it gives the error element is not clickable

**Comment by sakshamahluwalia** [comment]
This works as of Feb 2, 2022:
```
q_input = driver.find_element(By.NAME, "q")
q_input.send_keys(query, Keys.ENTER)
```
